apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: sg-springboot-deploy
spec:
  selector:
    app: sg-springboot-deploy
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: sg-springboot-deploy
spec:
  selector:
    matchLabels:
      app: sg-springboot-deploy
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: sg-springboot-deploy
    spec:
      containers:
      - name: sg-springboot-deploy
        image: sumitanandgupta/springboot:latest # Image that will be used inside the container in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # The port that the container is running on in the cluster
