name: Reusable Workflow Caller

on:
  push:
  workflow_dispatch:

jobs:
  Reusable-build-job:
    uses: ./.github/workflows/maven_build_reusable.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  Reusable-deploy-job:
    uses: ./.github/workflows/reusable_k8s_deploy.yml
    needs: Reusable-build-job
    secrets:
      KS_HOST: ${{ secrets.KS_HOST }}
      KS_HOST_USERNAME: ${{ secrets.KS_HOST_USERNAME }}
      KS_HOST_PASSWORD: ${{ secrets.KS_HOST_PASSWORD }}
      KS_HOST_PORT: ${{ secrets.KS_HOST_PORT }}
