#Reusable workflow to build application using Maven 

name: Reusable Build App with Maven

on:
  workflow_dispatch:
  workflow_call:
     secrets:
        DOCKERHUB_USERNAME:
          required: true
        DOCKERHUB_TOKEN:
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v3
      with:
       name: buildArtifact
       path: '${{ github.workspace }}/target/*'
    - name: Storing manifests in GitHub
      uses: actions/upload-artifact@v3
      with:
       name: k8smanifestsArtifacts
       path: '${{ github.workspace }}/k8smanifest/*'
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}:latest 
